spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres #${DB_HOST}:5432/${DB_NAME}
    username: postgres #{POSTGRES_USER}
    password: postgres #{POSTGRES_PASSWORD}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: create
